---
- name: Install nginx
  yum:
    name: nginx
    state: present


- name: copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart nginx
  tags: [nginx, config]

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes